version: "3.8"

services:
  api:
    container_name: golden-raspberry-api
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./application/.env
    restart: unless-stopped
    command: uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload
